// Package app contains transport-independent application services.
package app

import "errors"

var (
	ErrInvalidInput     = errors.New("invalid input")
	ErrNotFound         = errors.New("resource not found")
	ErrUnauthorized     = errors.New("unauthorized")
	ErrForbidden        = errors.New("forbidden")
	ErrUserBlocked      = errors.New("user is blocked")
	ErrSessionExpired   = errors.New("admin session expired")
	ErrStaleVersion     = errors.New("stale version")
	ErrConflict         = errors.New("resource conflict")
	ErrDuplicateUpdate  = errors.New("update already completed")
	ErrUpdateInProgress = errors.New("update is already processing")

	ErrInventoryNotFound        = errors.New("inventory item not found")
	ErrInventoryUnavailable     = errors.New("inventory item unavailable")
	ErrInsufficientInventory    = errors.New("insufficient inventory")
	ErrInventoryAlreadyExists   = errors.New("inventory item already exists")
	ErrInvalidInventoryState    = errors.New("invalid inventory state")
	ErrReservationNotOwned      = errors.New("reservation is not owned by order")
	ErrReservationExpired       = errors.New("inventory reservation expired")
	ErrUnsafeReservationRelease = errors.New("inventory reservation requires recovery")
	ErrEncryptionFailed         = errors.New("inventory encryption failed")
	ErrDecryptionFailed         = errors.New("inventory decryption failed")
	ErrUnknownKeyVersion        = errors.New("unknown inventory key version")
	ErrImportLimitExceeded      = errors.New("inventory import limit exceeded")
	ErrInvalidInventoryPayload  = errors.New("invalid inventory payload")

	ErrOrderNotFound             = errors.New("order not found")
	ErrOrderNotOwned             = errors.New("order not owned")
	ErrInvalidOrderState         = errors.New("invalid order state")
	ErrOrderExpired              = errors.New("order expired")
	ErrOrderAlreadyCancelled     = errors.New("order already cancelled")
	ErrInvalidQuantity           = errors.New("invalid quantity")
	ErrQuantityLimitExceeded     = errors.New("quantity limit exceeded")
	ErrMoneyOverflow             = errors.New("money calculation overflow")
	ErrProductInactive           = errors.New("product inactive")
	ErrCategoryInactive          = errors.New("category inactive")
	ErrBankAccountNotFound       = errors.New("bank account not found")
	ErrBankAccountInactive       = errors.New("bank account inactive")
	ErrDuplicateOrderOperation   = errors.New("order operation already completed")
	ErrPaymentReferenceCollision = errors.New("payment reference collision")
	ErrInvalidPaymentInstruction = errors.New("invalid payment instruction")
	ErrBankEncryptionFailed      = errors.New("bank account encryption failed")
	ErrBankDecryptionFailed      = errors.New("bank account decryption failed")
	ErrUnknownBankKeyVersion     = errors.New("unknown bank encryption key version")

	ErrInvalidWebhookSignature    = errors.New("invalid webhook signature")
	ErrWebhookReplay              = errors.New("webhook timestamp outside tolerance")
	ErrUnknownPaymentProvider     = errors.New("unknown payment provider")
	ErrDuplicatePaymentEvent      = errors.New("payment event already ingested")
	ErrPaymentEventConflict       = errors.New("payment event conflicts with stored evidence")
	ErrPaymentTransactionConflict = errors.New("payment transaction conflicts with stored evidence")
	ErrPaymentAlreadyAllocated    = errors.New("payment already allocated")
	ErrPaymentReferenceNotFound   = errors.New("payment reference not found")
	ErrPaymentAmountMismatch      = errors.New("payment amount mismatch")
	ErrPaymentCurrencyMismatch    = errors.New("payment currency mismatch")
	ErrPaymentTargetExpired       = errors.New("payment target expired")
	ErrLatePayment                = errors.New("late payment")
	ErrPaymentRequiresReview      = errors.New("payment requires review")
	ErrOrderAlreadyPaid           = errors.New("order already paid")
	ErrWalletNotFound             = errors.New("wallet not found")
	ErrInsufficientWalletBalance  = errors.New("insufficient wallet balance")
	ErrDuplicateLedgerOperation   = errors.New("wallet ledger operation already completed")
	ErrWalletTopUpNotFound        = errors.New("wallet top-up not found")
	ErrWalletTopUpExpired         = errors.New("wallet top-up expired")
	ErrInvalidWalletAmount        = errors.New("invalid wallet amount")
	ErrUnsafePaymentResolution    = errors.New("unsafe payment resolution")
)
